#!/bin/bash

#set -x
set -e
set -o pipefail
set -o nounset

script=./usr/bin/whonix-gateway-firewall.nftables
#script=./usr/bin/whonix-workstation-firewall.nftables

rm -f "${script}.nocomments"

while IFS= read -r line ; do
  line_without_leading_whitespace="${line#"${line%%[![:space:]]*}"}"
  read -r first _ <<< "$line_without_leading_whitespace" || true

  if [ "$first" = '$iptables_cmd' ] || [ "$first" = '#$iptables_cmd' ]; then
    continue
  fi

  echo "$line" | tee -a "${script}.nocomments" >/dev/null

done < "$script"
