#!/bin/sh

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

if [ -e "/usr/lib/qubes" ]; then
   true "$0: /usr/lib/qubes exits, exiting. See https://phabricator.whonix.org/T339 for details."
   exit 0
fi

/usr/bin/whonix_firewall
