#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category firewall and usability
#### description
## wrapper to open firewall examples
#### meta end

set -x

## https://bugzilla.xfce.org/show_bug.cgi?id=15282
## https://github.com/lxqt/lxqt-sudo/issues/114
## https://forums.whonix.org/t/use-sudoedit-in-whonix-documentation-and-whonix-software/7599/30

if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
  gsudoedit /etc/whonix_firewall.d/30_whonix_gateway_default.conf
else
  gsudoedit /etc/whonix_firewall.d/30_whonix_workstation_default.conf
fi
