#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category time and firewall
#### description
## restart firewall when sdwdate succeeded
#### meta end

#set -x
set -e

true "START: $0"

## inotifywait requires the folder to already exist.
mkdir --parents /run/updatesproxycheck
mkdir --parents /run/sdwdate
chown --recursive sdwdate:sdwdate /run/sdwdate

inotifywait_subshell_fifo="$(mktemp)"
inotifywait_process_pid=""
rm --force "$inotifywait_subshell_fifo"
mkfifo "$inotifywait_subshell_fifo"

cleanup() {
  if [ -p "$inotifywait_subshell_fifo" ]; then
    rm --force -- "$inotifywait_subshell_fifo"
  fi
  if [ -n "${inotifywait_process_pid:-}" ]; then
    kill "$inotifywait_process_pid" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

{
  inotifywait --quiet --recursive --monitor --event create --format "%w%f" "/run/sdwdate/" "/run/updatesproxycheck/" &
  ## This variable modification only happens inside the subshell.
  inotifywait_process_pid="$!"
  ## Necessary to terminate the inotifywait process itself.
  trap cleanup EXIT INT TERM
  wait "$inotifywait_process_pid"
} > "$inotifywait_subshell_fifo" &

inotifywait_process_pid="$!"

if [ -f "/run/sdwdate/first_success" ] || [ -f "/run/updatesproxycheck/whonix-secure-proxy" ]; then
  if systemctl --no-pager --no-block status whonix-firewall; then
    systemctl --no-pager --no-block restart whonix-firewall || true
  fi
fi

while read -r file_name; do
  if [ "$file_name" = "/run/sdwdate/first_success" ] || [ "$file_name" = "/run/updatesproxycheck/whonix-secure-proxy" ]; then
    if systemctl --no-pager --no-block status whonix-firewall; then
      systemctl --no-pager --no-block restart whonix-firewall || true
    fi
  fi
done < "$inotifywait_subshell_fifo"

wait "$inotifywait_process_pid"
