#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2017 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

## inotifywait requires the folder to already exist.
mkdir --parents /var/run/sdwdate
chown --recursive sdwdate:sdwdate /var/run/sdwdate

inotifywait --quiet --recursive --monitor --event create --format "%w%f" "/var/run/sdwdate/" "/var/run/qubes-service/" | while read file_name
do
    if [ "$file_name" = "/var/run/sdwdate/first_success" ] || [ "$file_name" = "/var/run/qubes-service/whonix-secure-proxy" ]; then
      if systemctl --no-pager --no-block status whonix-firewall ; then
         systemctl --no-pager --no-block restart whonix-firewall || true
      fi
    fi
done
