#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
   lxsu env XDG_CURRENT_DESKTOP=X-Generic xdg-open /etc/whonix_firewall.d/30_whonix_gateway_default.conf
else
   lxsu env XDG_CURRENT_DESKTOP=X-Generic xdg-open /etc/whonix_firewall.d/30_whonix_workstation_default.conf
fi
