#!/bin/bash

## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

## inotifywait requires the folder to already exist.
mkdir --parents /var/run/qubes-service
mkdir --parents /var/run/sdwdate
chown --recursive sdwdate:sdwdate /var/run/sdwdate

inotifywait_subshell_fifo="$(mktemp)"
rm --force "$inotifywait_subshell_fifo"
mkfifo "$inotifywait_subshell_fifo"

{
   inotifywait --quiet --recursive --monitor --event create --format "%w%f" "/var/run/sdwdate/" "/var/run/qubes-service/" &
   wait "$!"

} > "$inotifywait_subshell_fifo" &

inotifywait_subshell_pid="$!"

if [ -f "/var/run/sdwdate/first_success" ] || [ -f "/var/run/qubes-service/whonix-secure-proxy" ]; then
      if systemctl --no-pager --no-block status whonix-firewall ; then
         systemctl --no-pager --no-block restart whonix-firewall || true
      fi
fi

while read file_name; do
   if [ "$file_name" = "/var/run/sdwdate/first_success" ] || [ "$file_name" = "/var/run/qubes-service/whonix-secure-proxy" ]; then
      if systemctl --no-pager --no-block status whonix-firewall ; then
         systemctl --no-pager --no-block restart whonix-firewall || true
      fi
   fi
done < "$inotifywait_subshell_fifo"

wait "$inotifywait_subshell_pid"
