#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

lxsu env XDG_CURRENT_DESKTOP=X-Generic xdg-open /etc/whonix_firewall.d/50_user.conf
