#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category firewall and usability
#### description
## wrapper to open /etc/whonix_firewall.d/50_user.conf with sudoedit
#### meta end

set -x

sudoedit /etc/whonix_firewall.d/50_user.conf
