#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category firewall and usability
#### description
## wrapper to restart firewall
#### meta end

set -x

cat /etc/motd

sudo /usr/bin/whonix_firewall

true "$?"

true "Feel free to close this window."

sleep 86400
