#!/bin/bash

## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

cat /etc/motd

sudo /usr/bin/whonix_firewall

true "$?"

true "Feel free to close this window."

sleep 86400
